# Generated by Django 4.1 on 2023-01-16 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", web.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="bug",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bugs_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
