# Generated by Django 4.1 on 2023-01-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_user_managers_alter_bug_closed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
